### PR TITLE
According to the laravel documentation Eager Load relationships doesn't work with cursors. Suggested using lazy

### PR DESCRIPTION
**Pull request by naczu**
changed cursor method to lazy to run eager load relationships

### CODE REVIEW

**Comment by Jeroen-G** [comment]
One of the checks failed, could you take a look?

**Comment by naczu** [comment]
php version error

**Comment by naczu** [comment]
it seems it is about php version. the composer package doesn't support 7.4.  When I check the log PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/runner/work/Explorer/Explorer/vendor/spatie/macroable/src/Macroable.php:14

**Comment by Jeroen-G** [comment]
What do you mean? The package does support 7.4 as far as I know.

**Comment by naczu** [comment]
Can you run workflow again please. I just added comment to the code to be sure the error reason is lazy method or not.

**Comment by Jeroen-G** [comment]
Sure!

**Comment by Jeroen-G** [comment]
I think you can also run the actions in your own repo, that might speed things up for you.

**Pull request closed without merging**
