### PR TITLE
Cusrsor to lazy

### PR DESCRIPTION
**Pull request by naczu**
Just checked the workflows it's all passed. I have changed cursor method to lazy in ElasticEngine.php

### CODE REVIEW

**Comment by naczu** [comment]
According to the laravel documentation Eager Load relationships doesn't work with cursors. Suggested using lazy.

**Comment by Jeroen-G** [comment]
Cool. Do you have a link to the Laravel docs where you read that?

**Comment by Jeroen-G** [comment]
If you merge back or rebase from master the actions should work again.

**Comment by naczu** [comment]
Here is the documentation. Actually I don't understand why workflow is failing. I fetched the latest updates.
https://laravel.com/docs/8.x/eloquent#cursors

Screenshot 2021-12-11 235613

**Comment by Jeroen-G** [comment]
The workflows are now 🟢

**Pull request merged**
