### PR TITLE
New features

### PR DESCRIPTION
**Pull request by Seriyyy95**
Add highlight() method
Add collapse() method
Add orderByNested method with support filtering
Add scout prefix env value for indexes
Add getting result from single-value aggregations
Add getting result from multi-level aggregations
Add scout prefix support
Add search in two or more models
Parameter fields replaced by _source

Examples:

```
$result = Test::search()
   ->orderByNested('column_9.value', 'desc', ['column_9.name' => 'bbbb'])
   ->get();
```

```
$result = Test::search('omnis')
  ->collapse('column_6')
  ->highlight('column_6')
  ->raw();
```

```
$result = Test::search()
   ->aggregation('max_value', new MaxAggregation('column_1'))
   ->raw();
```

```
$agg = new NestedAggregation('column_9');
$agg->add('max', new MaxAggregation('column_9.value'));
$result = Test::search()
    ->aggregation('values', $agg)
    ->raw();
```

```
$indicesArray = [
   (new Item())->searchableAs(),
   (new Test())->searchableAs(),
];
$result = MixedSearch::search()
   ->orderBy('column_1')
   ->within(
      implode(',', $indicesArray)
   )
   ->get();
```

### CODE REVIEW

**Comment by Jeroen-G** [comment]
Thank you, that is quite an impressive contribution!
There are some mutations that the tests are not yet covering, you could take a look at those. However, I am going to check out the features and whether I'd like them all to be incorporated into the package. 👍 

For next time: A commit or PR per feature makes it easier/faster to review and merge :)

**Comment by Seriyyy95** [comment]
What tests should I do?

**Comment by Jeroen-G** [comment]
If you scroll through files changed you will see some warnings. You can also run `make mutations` locally in the codebase. But please, only if you want to learn from it for now, because I am not yet sure I want all the features :)

**Comment by Jeroen-G** [comment]
There are a few things you can do in your own domain and a few I want to support from the package. There are two options: you create separate PRs or I copy-paste from this PR (which means you lose the commit contribution on github). Features I think I'm interested in to start with are the scout prefix, max aggregation and nested aggregation.

**Comment by Seriyyy95** [comment]
I think u can copy-paste it. Now I have no time to refactor code.

**Pull request closed without merging**
