### PR TITLE
Upgrade to php 8.2

### PR DESCRIPTION
**Pull request by oortalabelgrup**

### CODE REVIEW

**Comment by askdkc** [comment]
@Jeroen-G 

When will this PR merged version be released? When I try to install this package on PHP 8.2 environment, I got following errors:

```bash
composer require jeroen-g/explorer

Cannot use jeroen-g/explorer's latest version 3.3.1 as it requires php 8.0.*||8.1.* which is not satisfied by your platform.
./composer.json has been updated
Running composer update jeroen-g/explorer
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jeroen-g/explorer[v1.0.0, ..., v1.2.0, v2.0.0, ..., 2.6.0] require illuminate/support ~7|~8 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - jeroen-g/explorer[3.0.0, ..., 3.3.1] require php 8.0.*||8.1.* -> your php version (8.2.1) does not satisfy that requirement.
    - Root composer.json requires jeroen-g/explorer * -> satisfiable by jeroen-g/explorer[v1.0.0, v1.0.1, v1.1.0, v1.2.0, v2.0.0, ..., 2.6.0, 3.0.0, ..., 3.3.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require jeroen-g/explorer:*" to figure out if any version is installable, or "composer require jeroen-g/explorer:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Although there is a workaround for this:
```bash
composer require jeroen-g/explorer:"dev-master"
```

But if you officially release the update, that would be wonderful😃

**Comment by Jeroen-G** [comment]
Does your application work on dev-master without any issues?

**Comment by askdkc** [comment]
@Jeroen-G 

So far, yes.

I mainly use this package to create index data for Elasticsearch from my Laravel models so that not all features are tested.

BTW, while using search function, php gives a warning:

`PHP Deprecated:
Creation of dynamic property
Laravel\Scout\Builder::$must is deprecated in /vendor/jeroen-
g/explorer/src/ExplorerServiceProvider. `

**Comment by Jeroen-G** [comment]
Hmm, can you make that a new issue? 🤔 
If possible with the whole stack trace if you have that.

**Comment by Jeroen-G** [comment]
https://github.com/Jeroen-G/Explorer/releases/tag/3.4.0
 
Enjoy! 🚀

**Comment by askdkc** [comment]
> Hmm, can you make that a new issue? 🤔 If possible with the whole stack trace if you have that.

OK, I created this [new issue](https://github.com/Jeroen-G/Explorer/issues/158).

**Pull request merged**
