### PR TITLE
Index updater

### PR DESCRIPTION
**Pull request by blackshadev**
Added a way to update indices gracefully. 

This is done by using ElasticSearch aliases. There are three aliases a read alias, a write alias and an history alias. The history  aggregates all old indices. These can be pruned with 'prune_old_aliases'. The read alias is  used for reading, the write index is used for writing. 

When updating an index it is recreated to a new index with a unique name. The "write" alias is pointed to the new index. All scout updates will be forwarded to the "write" index. After all entities are imported the "read" alias will also be pointed to the new index.

### CODE REVIEW

**Comment by blackshadev** [comment]
@Jeroen-G Mutations fail on an strict comparison. But I do not know how to introduce a test for that situation. If I remove the strict check , the codestyle will fail

**Review by Jeroen-G — APPROVED** [review]

**Comment by Jeroen-G** [comment]
@blackshadev unfortunately it does not functionally seem to work. At least `make refresh` did not work for the demo app: https://github.com/Jeroen-G/explorer-demo/pull/5/

**Comment by blackshadev** [comment]
> @blackshadev unfortunately it does not functionally seem to work. At least `make refresh` did not work for the demo app: [Jeroen-G/explorer-demo#5](https://github.com/Jeroen-G/explorer-demo/pull/5)

When I try your demo app and run `make refresh` I get 
```
Please install the Algolia client: algolia/algoliasearch-client-php
```

What do you get that as well? Do you know how to resolve it?

**Comment by blackshadev** [comment]
> @blackshadev unfortunately it does not functionally seem to work. At least `make refresh` did not work for the demo app: [Jeroen-G/explorer-demo#5](https://github.com/Jeroen-G/explorer-demo/pull/5)

You need some extra documentation on your demo app. I needed to change the driver to elastic in the configuration.

What error did you get? `{"error":"alias [cartographers-write] missing","status":404}`?

**Comment by blackshadev** [comment]
I applied some fixed. But I am unable to get the demo app working. I also copied .env.example to .env , but after running `sail up`, it still won't work. I get an error regarding the mysql database: `Connection refused (SQL: select * from `cartographers` order by `id` asc limit 500)`

**Pull request merged**
