### PR TITLE
Add Basic Auth.

### PR DESCRIPTION
**Pull request by bastienu**
See #97.

Not sure I made it well, and not sure if I have to merge with master.
I made my change from last commit of tag v2.5.0.
I wanted to make a PR on "tag" but obviously not possible...

### CODE REVIEW

**Comment by Jeroen-G** [comment]
I have created the branch `2.6.0` for you to target instead of master!

**Comment by bastienu** [comment]
Perfect, thanks !

**Comment by bastienu** [comment]
Oh.... I took the tag [2.5.0](https://github.com/Jeroen-G/Explorer/releases/tag/v2.5.0), and not the [2.5.1](https://github.com/Jeroen-G/Explorer/releases/tag/2.5.1).
Do you want me close this PR and make another one with the correct commit? Or maybe you can merge everything in the 2.6.0 branch?

Sorry !

**Comment by Jeroen-G** [comment]
There's no problem as far as I can see!

**Comment by bastienu** [comment]
Perfect, so can you merge and close ? 😇

**Pull request merged**
