### PR TITLE
Added PHP 8.3 Support

### PR DESCRIPTION
**Pull request by thecaliskan**

### CODE REVIEW

**Comment by Jeroen-G** [comment]
Thanks! For the contributing medal🏅 : could you update the workflows so 8.3 is with the others and no longer experimental and add 8.4 as experimental?

**Comment by thecaliskan** [comment]
I added 8.3 and 8.4 to workflow. I also added information to the changelog.md file.

Thanks @Jeroen-G

**Comment by Jeroen-G** [comment]
Thank you 🙏

**Comment by Jeroen-G** [comment]
Released as 3.11.0

**Pull request merged**
