### PR TITLE
Update index alias on queue

### PR DESCRIPTION
**Pull request by frizikk**
Hi,

Issue:
Alias substitution is happening too quickly (after sending all the documents to the queue), not all documents will be indexed in Elasticsearch.

Solution:
Delay the alias substitution by queuing the job. The substitution will occur when all or most of the documents have been indexed.

### CODE REVIEW

**Comment by blackshadev** [comment]
It really baffles me that someone didn't catch this earlier (or me for that matter). Unfortunately your code really isn't up to our standards. If the tests passed I could argue that I would fix it later, but in this case I cannot. 

I will try to iterate on your work, such that your commit remains in the codebase. If not I will create another PR and reference this PR and your name in it.

What I mean with our standards:
- We try to dependency inject everything we can instead of using global functions like `dispatch`
- We try to separate concerns if we can help it. In this case I would rename your event something like "FinishIndex" with the index name in it, no handle and let a separate listener do the handling.
- Add tests
- Adhere to codestyling

**Comment by blackshadev** [comment]
@Jeroen-G This should do it, can you check?

**Comment by frizikk** [comment]
@Jeroen-G bump

**Comment by Jeroen-G** [comment]
Merged into master for beta testing!

**Comment by frizikk** [comment]
hurray, it's going to production on Monday

**Pull request merged**
