### PR TITLE
add params for feature #86

### PR DESCRIPTION
**Pull request by chengxianga2008**

### CODE REVIEW

**Comment by Jeroen-G** [comment]
There are no tests.

**Comment by chengxianga2008** [comment]
Hi @Jeroen-G 
I have added test, please run CI again.

**Comment by chengxianga2008** [comment]
hello, I tested git action on your CI, it is working on my fork
can you try again, @Jeroen-G

**Comment by Jeroen-G** [comment]
Sure thing! Only the PR has to be open.

**Pull request closed without merging**
